### ISSUE TITLE
I think data preprocessing of AttnIO is wrong.

### ISSUE THREAD

**Issue by CedarSnowy** [rajbsk/kg-cruse#2]
Hello!I'am using _attnio_ code you implemented.Thank you for your work first!
However,I think the processing for _**start_entities**_  in **data_builder_dialkg_new.process_opendialkg_dataset** is wrong.According to AttnIO paper,_**start_entities**_  should appear in the final round of dialogue,but you append entities in the previous round of conversation.
So.I think should delete folloing code in **line 112 and 113:**

```python
for triple in kg_path:  
    starting_entities.add(triple[2])
```

**Comment by rajbsk** [comment]
It should be noted that the input and output of all the models need to be the same for comparison. We follow the guidelines from the OpenDialKG paper for the dataset preprocessing.

**Comment by CedarSnowy** [comment]
I looked at Opendialkg paper and found the following description, it looks like the start entity should only exist in the current turn：
_Each input is composed of three modalities: x = {xe; xs; xd}, where xe = {x(i) e } is a set of entities mentioned in the current turn, xs is its surrounding sentence context in the same turn, and xd is its dialog context up to the previous turn._

**Comment by rajbsk** [comment]
Exactly, now _xe_ is basically the set of entities mentioned in the current turn. The first sentence in the next paragraph quotes " Each output is a KG path sequence that connects x with entities mentioned in the next turn", thereby denoting that the terminal entity of the path is ideally present in the next turn, although there might not be exact lexical match. In fact, the official Opendialkg repo states the following: "Given utterance_1, utterance_2, and their annotated entity path A -> B -> C that connect utterance_1 and utterance_2, Entity A is assumed to be mentioned in utterance_1, and C to be mentioned in utterance_2."
